spring:
  cloud:
    nacos:
      server-addr: ${nacos.host:docker-server}:${nacos.port:8848}
      discovery:
        group: ${nacos.group:athena}
        namespace: ${nacos.namespace:dev}
      config:
        group: ${nacos.group:athena}
        namespace: ${nacos.namespace:dev}
  config:
    import:
      - optional:nacos:application-${spring.profiles.active:dev}.yml?refresh=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active:dev}.yml?refresh=true

logging:
  level:
    org.springframework: debug
    com.gls.athena: debug
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl