spring:
  cloud:
    nacos:
      server-addr: ${nacos.host:docker-server}:${nacos.port:8848}
      discovery:
        group: ${nacos.group:athena}
        namespace: ${nacos.namespace:4dd79b66-6b0d-46ba-8466-2fef2497f5b8}
      config:
        group: ${nacos.group:athena}
        namespace: ${nacos.namespace:4dd79b66-6b0d-46ba-8466-2fef2497f5b8}
        file-extension: yml
        shared-configs:
          - data-id: application.yml
            group: ${nacos.group:athena}
            refresh: true
          - data-id: application-${spring.profiles.active:dev}.yml
            group: ${nacos.group:athena}
            refresh: true
          - data-id: ${spring.application.name}-${spring.profiles.active:dev}.yml
            group: ${nacos.group:athena}
            refresh: true